server:
  port: 9090
spring:
  data:
    rest:
      base-path: /api 
  thymeleaf:
     prefix: classpath:/static/     
eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5      

# spring.thymeleaf.prefix=classpath:/templates/  Prefix that gets prepended to view names when building a URL.

      
      
       
      
